### ISSUE TITLE
Opening room 

### ISSUE THREAD

**Issue by Maddy-bee** [SchoolOfCode/week-1-hackathon-room-10-week1#2]
```[tasklist]
### Tasks
- [x] Create Backdrop
- [x] Create Title
- [x] Create button to open instructions with functionality
- [x] Write welcome instructions and add these to game
- [x] Create play button that takes you to the next room
- [x] create button to confirm instructions
- [x] Test whole of first room
- [x] Stretch goal: Tidy up cosmetics for buttons and text
```
