### ISSUE TITLE
Potions Room 

### ISSUE THREAD

**Issue by Maddy-bee** [SchoolOfCode/week-1-hackathon-room-10-week1#3]
This room holds the potions task. We will design it so that at first, when 2 potions are mixed correctly, you can proceed to the next stage. Depending on how difficult or time consuming it is to do this, we will change this to three potions to increase the difficulty of the game (stretch goal). 

```[tasklist]
### Tasks
- [x] Create potions room backdrop
- [x] Create Sprite character to give instructions
- [x] Write instructions for task and add to page
- [x] Create potion sprite x3
- [x] Create 'Mix' button
- [x] Create function to move potion sprite x3
- [x] Create If statement for correct mix
- [x] create else statement for incorrect mix
- [x] Create function to send on pathway to next stage
- [x] Test whole room
- [ ] Stretch goal: add function to start timer
- [ ] Stretch goal: add x3 more potions to increase difficulty
- [ ] Stretch goal: add voice to wizard
```
