### ISSUE TITLE
Stretch goals

### ISSUE THREAD

**Issue by BeardedGrinn** [SchoolOfCode/week-1-hackathon-room-10-week1#5]
```[tasklist]
### Tasks
- [x] Add sounds
- [ ] Add extra potions
- [ ] Add visual effects
- [ ] Add voice to wizard
- [ ] Add extra escape room puzzle
- [ ] Add timer
```
